name: Auto_Money_Machine

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *' # Ye bot ko har 6 ghante mein restart karega

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requests
        run: pip install requests

      - name: Execute Bot
        run: python app.py
        
